# Generated by Django 3.1.2 on 2020-11-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201105_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tarefa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.tarefa'),
        ),
    ]
