# Generated by Django 3.1.2 on 2020-11-13 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_link_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tarefa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.tarefa'),
        ),
    ]
