# Generated by Django 3.1.2 on 2020-11-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tag_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucao',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
